version: '3'
services:
  app1:
    build:
      context: ./app
      dockerfile: Dockerfile.cpu
    ports:
      - 8080:8080
    networks:
      - mynetwork
  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - mynetwork
  redis:
    image: redis:latest
    ports:
      - 6379:6379
    networks:
      - mynetwork
networks:
  mynetwork:
    driver: bridge
