version: '3'
services:
  app1:
    build:
      context: ./app
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    networks:
      - mynetwork
  app2:
    build:
      context: ./app2
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    networks:
      - mynetwork

networks:
  mynetwork:
    driver: bridge
